version: "3"

services: 
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
    ports:
      - 9200:9200
      - 9300:9300
    environment: 
      - discovery.type=single-node
      - xpack.security.enabled=false
    networks: 
      - logging-network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.1.1
    ports: 
      - 5601:5601
    networks: 
      - logging-network

networks: 
  logging-network:
    driver: bridge
